//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoU3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bitacora_espe_u3Entities : DbContext
    {
        public bitacora_espe_u3Entities()
            : base("name=bitacora_espe_u3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<novelties> novelties { get; set; }
        public virtual DbSet<pending_tasks> pending_tasks { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<view_novelties> view_novelties { get; set; }
        public virtual DbSet<view_pending_task> view_pending_task { get; set; }
        public virtual DbSet<view_pending_tasks> view_pending_tasks { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
