//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoU3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pending_tasks
    {
        public int id { get; set; }
        public Nullable<System.DateTime> hour_create { get; set; }
        public Nullable<System.DateTime> hour_done { get; set; }
        public string pending_task { get; set; }
        public Nullable<bool> task_done { get; set; }
        public Nullable<int> userCreate_id { get; set; }
        public Nullable<int> userDone_id { get; set; }
        public string observations { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
