//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoU3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.novelties = new HashSet<novelties>();
            this.pending_tasks = new HashSet<pending_tasks>();
            this.pending_tasks1 = new HashSet<pending_tasks>();
        }
    
        public int id { get; set; }
        public string blood_type { get; set; }
        public string email { get; set; }
        public string identification_card { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string last_names { get; set; }
        public string names { get; set; }
        public string password_users { get; set; }
        public string phone { get; set; }
        public string url_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<novelties> novelties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pending_tasks> pending_tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pending_tasks> pending_tasks1 { get; set; }
    }
}
