//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoU3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_novelties
    {
        public string novelty { get; set; }
        public Nullable<System.DateTime> hour { get; set; }
        public string guard { get; set; }
    }
}
