//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoU3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_pending_tasks
    {
        public string pending_tasks { get; set; }
        public Nullable<System.DateTime> hour_create { get; set; }
        public Nullable<System.DateTime> hour_done { get; set; }
        public string guardCreate { get; set; }
        public string guardDone { get; set; }
        public string observations { get; set; }
    }
}
